### ISSUE TITLE
idf V3.3 下编译通过，烧录设备后启动出错，一直在重启

### ISSUE THREAD

**Issue by jiekechoo** [gl-inet/s10#1]
B?ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:6328
load:0x40078000,len:11624
load:0x40080400,len:6676
entry 0x40080764
I (29) boot: ESP-IDF v3.3 2nd stage bootloader
I (29) boot: compile time 13:42:43
I (29) boot: Enabling RNG early entropy source...
I (34) boot: SPI Speed      : 80MHz
I (38) boot: SPI Mode       : DIO
I (42) boot: SPI Flash Size : 4MB
I (46) boot: Partition Table:
I (49) boot: ## Label            Usage          Type ST Offset   Length
I (57) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (64) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (72) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (79) boot:  3 ota_0            OTA app          00 10 00010000 001f0000
I (86) boot:  4 ota_1            OTA app          00 11 00200000 001f0000
I (94) boot: End of partition table
I (98) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x3982c (235564) map
I (176) esp_image: segment 1: paddr=0x00049854 vaddr=0x3ffbdb60 size=0x03784 ( 14212) load
I (181) esp_image: segment 2: paddr=0x0004cfe0 vaddr=0x40080000 size=0x00400 (  1024) load
0x40080000: _WindowOverflow4 at /Users/jiekechoo/esp/esp-idf/components/freertos/xtensa_vectors.S:1779

I (183) esp_image: segment 3: paddr=0x0004d3e8 vaddr=0x40080400 size=0x02c28 ( 11304) load
I (195) esp_image: segment 4: paddr=0x00050018 vaddr=0x400d0018 size=0xe4fb8 (937912) map
0x400d0018: _flash_cache_start at ??:?

I (473) esp_image: segment 5: paddr=0x00134fd8 vaddr=0x40083028 size=0x13964 ( 80228) load
0x40083028: coex_core_request at ??:?

I (515) boot: Loaded app from partition at offset 0x10000
I (515) boot: Disabling RNG early entropy source...
I (516) cpu_start: Pro cpu up.
I (519) cpu_start: Application information:
I (524) cpu_start: Project name:     gl-s10
I (529) cpu_start: App version:      1.0.0
I (534) cpu_start: Compile time:     Feb  9 2021 13:41:56
I (540) cpu_start: ELF file SHA256:  19767b7524b23c5a...
I (546) cpu_start: ESP-IDF:          v3.3
I (551) cpu_start: Starting app cpu, entry point is 0x4008114c
0x4008114c: call_start_cpu1 at /Users/jiekechoo/esp/esp-idf/components/esp32/cpu_start.c:270

I (0) cpu_start: App cpu up.
I (561) heap_init: Initializing. RAM available for dynamic allocation:
I (568) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM
I (574) heap_init: At 3FFB6388 len 00001C78 (7 KiB): DRAM
I (580) heap_init: At 3FFB9A20 len 00004108 (16 KiB): DRAM
I (586) heap_init: At 3FFBDB5C len 00000004 (0 KiB): DRAM
I (592) heap_init: At 3FFCF5B0 len 00010A50 (66 KiB): DRAM
I (598) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (605) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (611) heap_init: At 4009698C len 00009674 (37 KiB): IRAM
I (617) cpu_start: Pro cpu start user code
I (299) cpu_start: Chip Revision: 1
I (300) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (367) BTDM_INIT: BT controller compile version [e736f10]
I (367) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE

B?ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:6328
load:0x40078000,len:11624
load:0x40080400,len:6676
entry 0x40080764
I (29) boot: ESP-IDF v3.3 2nd stage bootloader
I (29) boot: compile time 13:42:43
I (29) boot: Enabling RNG early entropy source...
I (34) boot: SPI Speed      : 80MHz
I (38) boot: SPI Mode       : DIO
I (42) boot: SPI Flash Size : 4MB
I (46) boot: Partition Table:
I (49) boot: ## Label            Usage          Type ST Offset   Length
I (57) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (64) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (72) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (79) boot:  3 ota_0            OTA app          00 10 00010000 001f0000
I (86) boot:  4 ota_1            OTA app          00 11 00200000 001f0000
I (94) boot: End of partition table
I (98) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x3982c (235564) map
I (176) esp_image: segment 1: paddr=0x00049854 vaddr=0x3ffbdb60 size=0x03784 ( 14212) load
I (181) esp_image: segment 2: paddr=0x0004cfe0 vaddr=0x40080000 size=0x00400 (  1024) load
0x40080000: _WindowOverflow4 at /Users/jiekechoo/esp/esp-idf/components/freertos/xtensa_vectors.S:1779

I (183) esp_image: segment 3: paddr=0x0004d3e8 vaddr=0x40080400 size=0x02c28 ( 11304) load
I (195) esp_image: segment 4: paddr=0x00050018 vaddr=0x400d0018 size=0xe4fb8 (937912) map
0x400d0018: _flash_cache_start at ??:?

**Comment by HeFeng1947** [comment]
> B?ets Jun 8 2016 00:22:57
> 
> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
> configsip: 0, SPIWP:0xee
> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> mode:DIO, clock div:1
> load:0x3fff0018,len:4
> load:0x3fff001c,len:6328
> load:0x40078000,len:11624
> load:0x40080400,len:6676
> entry 0x40080764
> I (29) boot: ESP-IDF v3.3 2nd stage bootloader
> I (29) boot: compile time 13:42:43
> I (29) boot: Enabling RNG early entropy source...
> I (34) boot: SPI Speed : 80MHz
> I (38) boot: SPI Mode : DIO
> I (42) boot: SPI Flash Size : 4MB
> I (46) boot: Partition Table:
> I (49) boot: ## Label Usage Type ST Offset Length
> I (57) boot: 0 nvs WiFi data 01 02 00009000 00004000
> I (64) boot: 1 otadata OTA data 01 00 0000d000 00002000
> I (72) boot: 2 phy_init RF data 01 01 0000f000 00001000
> I (79) boot: 3 ota_0 OTA app 00 10 00010000 001f0000
> I (86) boot: 4 ota_1 OTA app 00 11 00200000 001f0000
> I (94) boot: End of partition table
> I (98) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x3982c (235564) map
> I (176) esp_image: segment 1: paddr=0x00049854 vaddr=0x3ffbdb60 size=0x03784 ( 14212) load
> I (181) esp_image: segment 2: paddr=0x0004cfe0 vaddr=0x40080000 size=0x00400 ( 1024) load
> 0x40080000: _WindowOverflow4 at /Users/jiekechoo/esp/esp-idf/components/freertos/xtensa_vectors.S:1779
> 
> I (183) esp_image: segment 3: paddr=0x0004d3e8 vaddr=0x40080400 size=0x02c28 ( 11304) load
> I (195) esp_image: segment 4: paddr=0x00050018 vaddr=0x400d0018 size=0xe4fb8 (937912) map
> 0x400d0018: _flash_cache_start at ??:?
> 
> I (473) esp_image: segment 5: paddr=0x00134fd8 vaddr=0x40083028 size=0x13964 ( 80228) load
> 0x40083028: coex_core_request at ??:?
> 
> I (515) boot: Loaded app from partition at offset 0x10000
> I (515) boot: Disabling RNG early entropy source...
> I (516) cpu_start: Pro cpu up.
> I (519) cpu_start: Application information:
> I (524) cpu_start: Project name: gl-s10
> I (529) cpu_start: App version: 1.0.0
> I (534) cpu_start: Compile time: Feb 9 2021 13:41:56
> I (540) cpu_start: ELF file SHA256: 19767b7524b23c5a...
> I (546) cpu_start: ESP-IDF: v3.3
> I (551) cpu_start: Starting app cpu, entry point is 0x4008114c
> 0x4008114c: call_start_cpu1 at /Users/jiekechoo/esp/esp-idf/components/esp32/cpu_start.c:270
> 
> I (0) cpu_start: App cpu up.
> I (561) heap_init: Initializing. RAM available for dynamic allocation:
> I (568) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM
> I (574) heap_init: At 3FFB6388 len 00001C78 (7 KiB): DRAM
> I (580) heap_init: At 3FFB9A20 len 00004108 (16 KiB): DRAM
> I (586) heap_init: At 3FFBDB5C len 00000004 (0 KiB): DRAM
> I (592) heap_init: At 3FFCF5B0 len 00010A50 (66 KiB): DRAM
> I (598) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
> I (605) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
> I (611) heap_init: At 4009698C len 00009674 (37 KiB): IRAM
> I (617) cpu_start: Pro cpu start user code
> I (299) cpu_start: Chip Revision: 1
> I (300) cpu_start: Starting scheduler on PRO CPU.
> I (0) cpu_start: Starting scheduler on APP CPU.
> I (367) BTDM_INIT: BT controller compile version [e736f10]
> I (367) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
> 
> B?ets Jun 8 2016 00:22:57
> 
> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
> configsip: 0, SPIWP:0xee
> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> mode:DIO, clock div:1
> load:0x3fff0018,len:4
> load:0x3fff001c,len:6328
> load:0x40078000,len:11624
> load:0x40080400,len:6676
> entry 0x40080764
> I (29) boot: ESP-IDF v3.3 2nd stage bootloader
> I (29) boot: compile time 13:42:43
> I (29) boot: Enabling RNG early entropy source...
> I (34) boot: SPI Speed : 80MHz
> I (38) boot: SPI Mode : DIO
> I (42) boot: SPI Flash Size : 4MB
> I (46) boot: Partition Table:
> I (49) boot: ## Label Usage Type ST Offset Length
> I (57) boot: 0 nvs WiFi data 01 02 00009000 00004000
> I (64) boot: 1 otadata OTA data 01 00 0000d000 00002000
> I (72) boot: 2 phy_init RF data 01 01 0000f000 00001000
> I (79) boot: 3 ota_0 OTA app 00 10 00010000 001f0000
> I (86) boot: 4 ota_1 OTA app 00 11 00200000 001f0000
> I (94) boot: End of partition table
> I (98) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x3982c (235564) map
> I (176) esp_image: segment 1: paddr=0x00049854 vaddr=0x3ffbdb60 size=0x03784 ( 14212) load
> I (181) esp_image: segment 2: paddr=0x0004cfe0 vaddr=0x40080000 size=0x00400 ( 1024) load
> 0x40080000: _WindowOverflow4 at /Users/jiekechoo/esp/esp-idf/components/freertos/xtensa_vectors.S:1779
> 
> I (183) esp_image: segment 3: paddr=0x0004d3e8 vaddr=0x40080400 size=0x02c28 ( 11304) load
> I (195) esp_image: segment 4: paddr=0x00050018 vaddr=0x400d0018 size=0xe4fb8 (937912) map
> 0x400d0018: _flash_cache_start at ??:?


看一下make menuconfig--->Component config--->eFuse Bit Manager--->Coding Scheme Compatibility，是否设置成None Only

**Comment by jiekechoo** [comment]
按照你的提示修改完成，可以启动了。谢谢

**Comment by jiekechoo** [comment]
现在发现，重启那台还是在不停的重启。

**Comment by jiekechoo** [comment]
最终确认是供电电压不稳定造成。
