### ISSUE TITLE
Source codes of s10_configuration_tool.apk

### ISSUE THREAD

**Issue by ruslanslobozhenuk** [gl-inet/s10#2]
Please post the source codes of s10_configuration_tool.apk. It's not entirely clear how the application works. Some modes are not available.

**Comment by Hoff-GLiNet** [comment]
Those code isn't open source,  which modes do you use?

**Comment by ruslanslobozhenuk** [comment]
When I install the SSID, the android application does not react in any way. The situation is the same with MQTT.

The code shows that the notification should be sent, but the application does not seem to receive it. I have a task to write a gateway between BLE mesh and ethernet, so the standard firmware is not suitable ((((

**Comment by Hoff-GLiNet** [comment]
This s10 code is old, we don't maintain this code, so the app can't set the this firmware. If you want to need s10 new code, you can   cantact the 2B team. 2B team email: raya.ren@gl-inet.com

**Comment by ruslanslobozhenuk** [comment]
Thank YOU!
